apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiga.fullname" . }}-taiga-frontend-env-vars
type: Opaque
data:
  {{- if .Values.frontend.extraEnv }}
  {{- range $key, $val := .Values.frontend.extraEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
