apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiga.fullname" . }}-taiga-backend-env-vars
type: Opaque
data:
  {{- if .Values.smtp.enabled }}
  EMAIL_BACKEND: {{ printf "django.core.mail.backends.smtp.EmailBackend" | b64enc }}
  DEFAULT_FROM_EMAIL: {{ .Values.smtp.from | b64enc }}
  EMAIL_HOST: {{ .Values.smtp.host | b64enc }}
  EMAIL_PORT: {{ .Values.smtp.port | toString | b64enc }}
  EMAIL_HOST_USER: {{ .Values.smtp.username | b64enc }}
  EMAIL_HOST_PASSWORD: {{ .Values.smtp.password | b64enc }}
  EMAIL_USE_SSL: {{ .Values.smtp.useSSL | toString | b64enc }}
  {{- end }}
  {{- if .Values.backend.extraEnv }}
  {{- range $key, $val := .Values.backend.extraEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
