apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiga.fullname" . }}-taiga-backend-env-vars
type: Opaque
data:
  {{- if .Values.backend.extraEnv }}
  {{- range $key, $val := .Values.backend.extraEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
