apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiga.fullname" . }}-taiga-frontend-env-vars
type: Opaque
data:
  DEFAULT_LOGIN_ENABLED: {{ .Values.auth.defaultLoginEnabled | toString | b64enc | quote }}
  PUBLIC_REGISTER_ENABLED: {{ .Values.auth.publicRegisterEnabled | toString | b64enc | quote }}
  {{- if .Values.auth.oidc.enabled }}
  ENABLE_OIDC_AUTH: {{ .Values.auth.oidc.enabled | toString | b64enc | quote }}
  OIDC_BUTTON_TEXT: {{ .Values.auth.oidc.name | b64enc | quote }}
  OIDC_BUTTON_LOGO: {{  .Values.auth.oidc.logo | b64enc | quote }}
  {{- end }}
  {{- if .Values.frontend.extraEnv }}
  {{- range $key, $val := .Values.frontend.extraEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
