apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiga.fullname" . }}-taiga-env-vars
type: Opaque
data:
  TAIGA_SECRET_KEY: {{ .Values.secretKey | b64enc }}
  EVENTS_PUSH_BACKEND_URL: {{ printf "amqp://%s:%s@%s-rabbitmq:%d/%s" .Values.rabbitmq.auth.username .Values.rabbitmq.auth.password (include "taiga.fullname" .) (.Values.rabbitmq.service.ports.amqp | int) .Values.rabbitmq.vhost | b64enc }}
  CELERY_BROKER_URL: {{ printf "amqp://%s:%s@%s-rabbitmq:%d/%s" .Values.rabbitmq.auth.username .Values.rabbitmq.auth.password (include "taiga.fullname" .) (.Values.rabbitmq.service.ports.amqp | int) .Values.rabbitmq.vhost | b64enc }}
  RABBITMQ_URL: {{ printf "amqp://%s:%s@%s-rabbitmq:%d/%s" .Values.rabbitmq.auth.username .Values.rabbitmq.auth.password (include "taiga.fullname" .) (.Values.rabbitmq.service.ports.amqp | int) .Values.rabbitmq.vhost | b64enc }}
