apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiga.fullname" . }}-taiga-backend-env-vars
type: Opaque
data:
  {{- if .Values.smtp.enabled }}
  EMAIL_BACKEND: {{ print "django.core.mail.backends.smtp.EmailBackend" | b64enc }}
  DEFAULT_FROM_EMAIL: {{ .Values.smtp.from | b64enc }}
  EMAIL_HOST: {{ .Values.smtp.host | b64enc }}
  EMAIL_PORT: {{ .Values.smtp.port | toString | b64enc }}
  EMAIL_HOST_USER: {{ .Values.smtp.username | b64enc }}
  EMAIL_HOST_PASSWORD: {{ .Values.smtp.password | b64enc }}
  EMAIL_USE_SSL: {{ .Values.smtp.useSsl | toString | title | b64enc }}
  EMAIL_USE_TLS: {{ .Values.smtp.useTls | toString | title | b64enc }}
  {{- end }}
  PUBLIC_REGISTER_ENABLED: {{ .Values.auth.publicRegisterEnabled | toString | title | b64enc | quote }}
  USE_X_FORWARDED_HOST: {{ .Values.auth.useForwardedHost | toString | title | b64enc | quote }}
  {{- if .Values.auth.oidc.enabled }}
  ENABLE_OIDC_AUTH: {{ .Values.auth.oidc.enabled | toString | title | b64enc | quote }}
  OIDC_ISSUER: {{ .Values.auth.oidc.issuer | b64enc | quote }}
  OIDC_SCOPES: {{ .Values.auth.oidc.scopes | b64enc | quote }}
  OIDC_CLIENT_ID: {{ .Values.auth.oidc.clientId | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.auth.oidc.clientSecret | b64enc | quote }}
  {{- if .Values.auth.oidc.endpoints.authorization }}
  OIDC_AUTHORIZATION_ENDPOINT: {{ .Values.auth.oidc.endpoints.authorization | b64enc | quote}}
  {{- end }}
  {{- if .Values.auth.oidc.endpoints.token }}
  OIDC_TOKEN_ENDPOINT: {{ .Values.auth.oidc.endpoints.token | b64enc | quote}}
  {{- end }}
  {{- if .Values.auth.oidc.endpoints.userinfo }}
  OIDC_USERINFO_ENDPOINT: {{ .Values.auth.oidc.endpoints.userinfo | b64enc | quote}}
  {{- end }}
  {{- if .Values.auth.oidc.endpoints.jwks }}
  OIDC_JWKS_ENDPOINT: {{ .Values.auth.oidc.endpoints.jwks | b64enc | quote}}
  {{- end }}
  OIDC_AUTHDATA_KEY: {{ .Values.auth.oidc.authKey | toString | b64enc | quote }}
  OIDC_SLUGGIFY_USERNAME: {{ .Values.auth.oidc.sluggifyUserName | toString | title | b64enc | quote }}
  OIDC_CLAIM_AUTHDATA: {{ .Values.auth.oidc.claims.authData | toString | b64enc | quote }}
  OIDC_CLAIM_EMAIL: {{ .Values.auth.oidc.claims.email | toString | b64enc | quote }}
  OIDC_CLAIM_FULLNAME: {{ .Values.auth.oidc.claims.fullName | toString | b64enc | quote }}
  OIDC_CLAIM_USERNAME: {{ .Values.auth.oidc.claims.userName | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.extraEnv }}
  {{- range $key, $val := .Values.backend.extraEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
