apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiga.fullname" . }}-broker-credentials
type: Opaque
data:
  RABBITMQ_USER: {{ .Values.rabbitmq.auth.username | b64enc }}
  RABBITMQ_PASS: {{ .Values.rabbitmq.auth.password | b64enc }}
