apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiga.fullname" . }}-database-credentials
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgresql.postgresqlDatabase | b64enc }}
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc }}
