apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiga.fullname" . }}-database-credentials
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
